package com.mycompany.gui;

import com.mycompany.gui.menutienda.PokemonesJPanel;
import com.mycompany.gui.menutienda.MedicinaJPanel;
import com.mycompany.gui.menutienda.ComidaJPanel;
import com.mycompany.gui.opcionesayuda.*;
import javax.swing.JPanel;

/**
 *
 * @author michael
 */
public class VentanaPrincipalJFrame extends javax.swing.JFrame {

//    FondoFrame fondo = new FondoFrame();
    /**
     * Creates new form Frame
     */
    public VentanaPrincipalJFrame() {
        initComponents();
        setLocationRelativeTo(null);
//        this.setContentPane(fondo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        contenedorJPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        botonPasear = new javax.swing.JMenu();
        botonMiPoke = new javax.swing.JMenu();
        botonTienda = new javax.swing.JMenu();
        botonTiendaComida = new javax.swing.JMenuItem();
        botonTiendaMedicamentos = new javax.swing.JMenuItem();
        botonTiendaPokemones = new javax.swing.JMenuItem();
        botonRevirir = new javax.swing.JMenuItem();
        botonReportes = new javax.swing.JMenu();
        botonAyuda = new javax.swing.JMenu();
        botonAyudaPasearjMenuItem = new javax.swing.JMenuItem();
        botonAyudaMiPokejMenuItem = new javax.swing.JMenuItem();
        ayudaTiendajMenuItem = new javax.swing.JMenuItem();
        ayudaReportesjMenuItem = new javax.swing.JMenuItem();
        botonAcercaDe = new javax.swing.JMenu();

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pokemon Memory");

        contenedorJPanel.setLayout(new java.awt.CardLayout());

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));

        botonPasear.setForeground(new java.awt.Color(0, 0, 0));
        botonPasear.setText("Pasear");
        botonPasear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonPasear.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        botonPasear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPasearActionPerformed(evt);
            }
        });
        jMenuBar1.add(botonPasear);

        botonMiPoke.setForeground(new java.awt.Color(0, 0, 0));
        botonMiPoke.setText("Mi Poke");
        jMenuBar1.add(botonMiPoke);

        botonTienda.setForeground(new java.awt.Color(0, 0, 0));
        botonTienda.setText("Tienda");
        botonTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTiendaActionPerformed(evt);
            }
        });

        botonTiendaComida.setBackground(new java.awt.Color(0, 255, 153));
        botonTiendaComida.setForeground(new java.awt.Color(153, 102, 0));
        botonTiendaComida.setText("Comida");
        botonTiendaComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTiendaComidaActionPerformed(evt);
            }
        });
        botonTienda.add(botonTiendaComida);

        botonTiendaMedicamentos.setBackground(new java.awt.Color(51, 255, 153));
        botonTiendaMedicamentos.setForeground(new java.awt.Color(255, 0, 0));
        botonTiendaMedicamentos.setText("Medicina");
        botonTiendaMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTiendaMedicamentosActionPerformed(evt);
            }
        });
        botonTienda.add(botonTiendaMedicamentos);

        botonTiendaPokemones.setBackground(new java.awt.Color(102, 255, 153));
        botonTiendaPokemones.setForeground(new java.awt.Color(0, 153, 0));
        botonTiendaPokemones.setText("Pokemones");
        botonTiendaPokemones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTiendaPokemonesActionPerformed(evt);
            }
        });
        botonTienda.add(botonTiendaPokemones);

        botonRevirir.setBackground(new java.awt.Color(153, 255, 153));
        botonRevirir.setForeground(new java.awt.Color(255, 0, 0));
        botonRevirir.setText("Revivir Pokemon");
        botonRevirir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRevirirActionPerformed(evt);
            }
        });
        botonTienda.add(botonRevirir);

        jMenuBar1.add(botonTienda);

        botonReportes.setForeground(new java.awt.Color(0, 0, 0));
        botonReportes.setText("Reportes");
        botonReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReportesActionPerformed(evt);
            }
        });
        jMenuBar1.add(botonReportes);

        botonAyuda.setForeground(new java.awt.Color(0, 0, 0));
        botonAyuda.setText("Ayuda");
        botonAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAyudaActionPerformed(evt);
            }
        });

        botonAyudaPasearjMenuItem.setText("Pasear");
        botonAyudaPasearjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAyudaPasearjMenuItemActionPerformed(evt);
            }
        });
        botonAyuda.add(botonAyudaPasearjMenuItem);

        botonAyudaMiPokejMenuItem.setText("Mis Pokemones");
        botonAyudaMiPokejMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAyudaMiPokejMenuItemActionPerformed(evt);
            }
        });
        botonAyuda.add(botonAyudaMiPokejMenuItem);

        ayudaTiendajMenuItem.setText("Tienda");
        ayudaTiendajMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaTiendajMenuItemActionPerformed(evt);
            }
        });
        botonAyuda.add(ayudaTiendajMenuItem);

        ayudaReportesjMenuItem.setText("Reportes");
        ayudaReportesjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaReportesjMenuItemActionPerformed(evt);
            }
        });
        botonAyuda.add(ayudaReportesjMenuItem);

        jMenuBar1.add(botonAyuda);

        botonAcercaDe.setForeground(new java.awt.Color(0, 0, 0));
        botonAcercaDe.setText("Acerda de ...");
        botonAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAcercaDeActionPerformed(evt);
            }
        });
        jMenuBar1.add(botonAcercaDe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRevirirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRevirirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRevirirActionPerformed

    private void botonPasearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPasearActionPerformed
        // TODO add your handling code here:
        BatallaJPanel batalla = new BatallaJPanel();
        this.cambiarPanel(batalla);
    }//GEN-LAST:event_botonPasearActionPerformed

    private void botonTiendaComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTiendaComidaActionPerformed
        // TODO add your handling code here:
        ComidaJPanel comida = new ComidaJPanel();
        this.cambiarPanel(comida);
    }//GEN-LAST:event_botonTiendaComidaActionPerformed

    private void botonTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTiendaActionPerformed

    }//GEN-LAST:event_botonTiendaActionPerformed

    private void botonTiendaMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTiendaMedicamentosActionPerformed
        // TODO add your handling code here:
        MedicinaJPanel medicina = new MedicinaJPanel();
        this.cambiarPanel(medicina);
    }//GEN-LAST:event_botonTiendaMedicamentosActionPerformed

    private void botonTiendaPokemonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTiendaPokemonesActionPerformed
        // TODO add your handling code here:
        PokemonesJPanel pokemones = new PokemonesJPanel();
        this.cambiarPanel(pokemones);
    }//GEN-LAST:event_botonTiendaPokemonesActionPerformed

    private void botonReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReportesActionPerformed
        // TODO add your handling code here:
        ReportesJPanel reporte = new ReportesJPanel();
        this.cambiarPanel(reporte);
    }//GEN-LAST:event_botonReportesActionPerformed

    private void botonAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAcercaDeActionPerformed
        // TODO add your handling code here:
        AcercaDeJPanel info = new AcercaDeJPanel();
        this.cambiarPanel(info);
    }//GEN-LAST:event_botonAcercaDeActionPerformed

    private void botonAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAyudaActionPerformed

    }//GEN-LAST:event_botonAyudaActionPerformed

    private void botonAyudaPasearjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAyudaPasearjMenuItemActionPerformed
        // TODO add your handling code here:
        AyudaPasearJPanel ayudaPasear = new AyudaPasearJPanel();
        this.cambiarPanel(ayudaPasear);
    }//GEN-LAST:event_botonAyudaPasearjMenuItemActionPerformed

    private void botonAyudaMiPokejMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAyudaMiPokejMenuItemActionPerformed
        // TODO add your handling code here:
        AyudaMisPokemonesJPanel ayudaMiPoke = new AyudaMisPokemonesJPanel();
        this.cambiarPanel(ayudaMiPoke);
    }//GEN-LAST:event_botonAyudaMiPokejMenuItemActionPerformed

    private void ayudaReportesjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaReportesjMenuItemActionPerformed
        // TODO add your handling code here:
        AyudaReportesJPanel ayudaReportes = new AyudaReportesJPanel();
        this.cambiarPanel(ayudaReportes);
    }//GEN-LAST:event_ayudaReportesjMenuItemActionPerformed

    private void ayudaTiendajMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaTiendajMenuItemActionPerformed
        // TODO add your handling code here:
        AyudaTienda ayudaTienda = new AyudaTienda();
        this.cambiarPanel(ayudaTienda);
    }//GEN-LAST:event_ayudaTiendajMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ayudaReportesjMenuItem;
    private javax.swing.JMenuItem ayudaTiendajMenuItem;
    private javax.swing.JMenu botonAcercaDe;
    private javax.swing.JMenu botonAyuda;
    private javax.swing.JMenuItem botonAyudaMiPokejMenuItem;
    private javax.swing.JMenuItem botonAyudaPasearjMenuItem;
    private javax.swing.JMenu botonMiPoke;
    private javax.swing.JMenu botonPasear;
    private javax.swing.JMenu botonReportes;
    private javax.swing.JMenuItem botonRevirir;
    private javax.swing.JMenu botonTienda;
    private javax.swing.JMenuItem botonTiendaComida;
    private javax.swing.JMenuItem botonTiendaMedicamentos;
    private javax.swing.JMenuItem botonTiendaPokemones;
    private javax.swing.JPanel contenedorJPanel;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    public void cambiarPanel(JPanel panel) {
        contenedorJPanel.removeAll();
        contenedorJPanel.add(panel);
        contenedorJPanel.repaint();
        contenedorJPanel.revalidate();
    }

//    class FondoFrame extends JPanel {
//
//        private Image imagen;
//
//        @Override
//        public void paint(Graphics g) {
//            imagen = new ImageIcon(getClass().getResource("/com/mycompany/gui/imagenes/FondoFrame.png")).getImage();
//            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
//            setOpaque(false);
//            super.paint(g);
//        }
//    }
}
