package com.mycompany.gui;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author michael
 */
public class VentanaPrincipalJFrame extends javax.swing.JFrame {

    FondoFrame fondo = new FondoFrame();

    /**
     * Creates new form Frame
     */
    public VentanaPrincipalJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        this.setContentPane(fondo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        contenedorJPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        botonPasear = new javax.swing.JMenu();
        botonMiPoke = new javax.swing.JMenu();
        botonTienda = new javax.swing.JMenu();
        botonTiendaComida = new javax.swing.JMenuItem();
        botonTiendaMedicamentos = new javax.swing.JMenuItem();
        botonTiendaPokemones = new javax.swing.JMenuItem();
        botonRevirir = new javax.swing.JMenuItem();
        botonReportes = new javax.swing.JMenu();
        botonAcercaDe = new javax.swing.JMenu();
        botonAyuda = new javax.swing.JMenu();

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pokemon Memory");
        setPreferredSize(new java.awt.Dimension(920, 640));

        contenedorJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));

        botonPasear.setForeground(new java.awt.Color(0, 0, 0));
        botonPasear.setText("Pasear");
        botonPasear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonPasear.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        botonPasear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPasearActionPerformed(evt);
            }
        });
        jMenuBar1.add(botonPasear);

        botonMiPoke.setForeground(new java.awt.Color(0, 0, 0));
        botonMiPoke.setText("Mis Pokemones");
        jMenuBar1.add(botonMiPoke);

        botonTienda.setForeground(new java.awt.Color(0, 0, 0));
        botonTienda.setText("Tienda");

        botonTiendaComida.setBackground(new java.awt.Color(0, 255, 153));
        botonTiendaComida.setForeground(new java.awt.Color(153, 102, 0));
        botonTiendaComida.setText("Comida");
        botonTiendaComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTiendaComidaActionPerformed(evt);
            }
        });
        botonTienda.add(botonTiendaComida);

        botonTiendaMedicamentos.setBackground(new java.awt.Color(51, 255, 153));
        botonTiendaMedicamentos.setForeground(new java.awt.Color(255, 0, 0));
        botonTiendaMedicamentos.setText("Medicina");
        botonTienda.add(botonTiendaMedicamentos);

        botonTiendaPokemones.setBackground(new java.awt.Color(102, 255, 153));
        botonTiendaPokemones.setForeground(new java.awt.Color(0, 153, 0));
        botonTiendaPokemones.setText("Pokemones");
        botonTienda.add(botonTiendaPokemones);

        botonRevirir.setBackground(new java.awt.Color(153, 255, 153));
        botonRevirir.setForeground(new java.awt.Color(255, 0, 0));
        botonRevirir.setText("Revivir Pokemon");
        botonRevirir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRevirirActionPerformed(evt);
            }
        });
        botonTienda.add(botonRevirir);

        jMenuBar1.add(botonTienda);

        botonReportes.setForeground(new java.awt.Color(0, 0, 0));
        botonReportes.setText("Reportes");
        jMenuBar1.add(botonReportes);

        botonAcercaDe.setForeground(new java.awt.Color(0, 0, 0));
        botonAcercaDe.setText("Acerda de ...");
        jMenuBar1.add(botonAcercaDe);

        botonAyuda.setForeground(new java.awt.Color(0, 0, 0));
        botonAyuda.setText("Ayuda");
        jMenuBar1.add(botonAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRevirirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRevirirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRevirirActionPerformed

    private void botonPasearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPasearActionPerformed
        // TODO add your handling code here:
        BatallaJPanel batalla = new BatallaJPanel();
        batalla.setSize(880, 570);
        batalla.setLocation(0, 0);

        contenedorJPanel.removeAll();
        contenedorJPanel.add(batalla, BorderLayout.CENTER);
        contenedorJPanel.revalidate();
    }//GEN-LAST:event_botonPasearActionPerformed

    private void botonTiendaComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTiendaComidaActionPerformed
        // TODO add your handling code here:
        BatallaJPanel batalla = new BatallaJPanel();
        batalla.setSize(880, 570);
        batalla.setLocation(0, 0);

        contenedorJPanel.removeAll();
        contenedorJPanel.add(batalla, BorderLayout.CENTER);
        contenedorJPanel.revalidate();
    }//GEN-LAST:event_botonTiendaComidaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu botonAcercaDe;
    private javax.swing.JMenu botonAyuda;
    private javax.swing.JMenu botonMiPoke;
    private javax.swing.JMenu botonPasear;
    private javax.swing.JMenu botonReportes;
    private javax.swing.JMenuItem botonRevirir;
    private javax.swing.JMenu botonTienda;
    private javax.swing.JMenuItem botonTiendaComida;
    private javax.swing.JMenuItem botonTiendaMedicamentos;
    private javax.swing.JMenuItem botonTiendaPokemones;
    private javax.swing.JPanel contenedorJPanel;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    class FondoFrame extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/com/mycompany/gui/imagenes/FondoFrame.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
