package com.mycompany.gui;

/**
 *
 * @author michael
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        pasear = new javax.swing.JMenu();
        pokemones = new javax.swing.JMenu();
        tienda = new javax.swing.JMenu();
        tiendaComida = new javax.swing.JMenuItem();
        medicamentos = new javax.swing.JMenuItem();
        tiendaPokemones = new javax.swing.JMenuItem();
        revirir = new javax.swing.JMenuItem();
        reportes = new javax.swing.JMenu();
        acercaDe = new javax.swing.JMenu();
        ayuda = new javax.swing.JMenu();

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pokemon Memory");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 23, 712, 450));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        jMenuBar1.setBackground(new java.awt.Color(51, 255, 204));

        pasear.setForeground(new java.awt.Color(0, 51, 255));
        pasear.setText("Pasear");
        jMenuBar1.add(pasear);

        pokemones.setForeground(new java.awt.Color(51, 51, 255));
        pokemones.setText("Mis Pokemones");
        jMenuBar1.add(pokemones);

        tienda.setForeground(new java.awt.Color(51, 51, 255));
        tienda.setText("Tienda");

        tiendaComida.setBackground(new java.awt.Color(0, 255, 153));
        tiendaComida.setForeground(new java.awt.Color(153, 102, 0));
        tiendaComida.setText("Comida");
        tienda.add(tiendaComida);

        medicamentos.setBackground(new java.awt.Color(51, 255, 153));
        medicamentos.setForeground(new java.awt.Color(255, 0, 0));
        medicamentos.setText("Medicina");
        tienda.add(medicamentos);

        tiendaPokemones.setBackground(new java.awt.Color(102, 255, 153));
        tiendaPokemones.setForeground(new java.awt.Color(0, 153, 0));
        tiendaPokemones.setText("Pokemones");
        tienda.add(tiendaPokemones);

        revirir.setBackground(new java.awt.Color(153, 255, 153));
        revirir.setForeground(new java.awt.Color(255, 0, 0));
        revirir.setText("Revivir Pokemon");
        revirir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revirirActionPerformed(evt);
            }
        });
        tienda.add(revirir);

        jMenuBar1.add(tienda);

        reportes.setForeground(new java.awt.Color(51, 51, 255));
        reportes.setText("Reportes");
        jMenuBar1.add(reportes);

        acercaDe.setForeground(new java.awt.Color(51, 51, 255));
        acercaDe.setText("Acerda de ...");
        jMenuBar1.add(acercaDe);

        ayuda.setForeground(new java.awt.Color(51, 51, 255));
        ayuda.setText("Ayuda");
        jMenuBar1.add(ayuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void revirirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revirirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_revirirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu acercaDe;
    private javax.swing.JMenu ayuda;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem medicamentos;
    private javax.swing.JMenu pasear;
    private javax.swing.JMenu pokemones;
    private javax.swing.JMenu reportes;
    private javax.swing.JMenuItem revirir;
    private javax.swing.JMenu tienda;
    private javax.swing.JMenuItem tiendaComida;
    private javax.swing.JMenuItem tiendaPokemones;
    // End of variables declaration//GEN-END:variables

}
