/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.gui.opcionesayuda;

/**
 *
 * @author michael
 */
public class AyudaPasearJPanel extends javax.swing.JPanel {

    /**
     * Creates new form Pasear
     */
    public AyudaPasearJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Meslo LG L DZ for Powerline", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\t               -Pasear-\n\n· Al momento de sacar a pasear una mascota puede\n  encontrarse con algún pokemon salvaje, comenzará una\n  batalla donde es un juego de memorias, dependiendo\n  del nivel de su pokemon será la cantidad de pares de\n  cartas, gana el que tenga más parejas descubiertas.");
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, 200));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
