package com.mycompany.gui.opcionesayuda;

/**
 *
 * @author michael
 */
public class AyudaReportesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AyudaJPanel
     */
    public AyudaReportesJPanel() {
        initComponents();
        setSize(880, 570);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Meslo LG L DZ for Powerline", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("\t            -Reportes-\n\n· Muesta una tabla donde se indica los movimientos\n  hechos por cada mascota, como fecha de\n  nacimiento, partidas ganadas, veces que ha\n  enfermado, veces que ha comido, veces que ha\n  enfermado y cuando ha muerto.");
        jScrollPane1.setViewportView(jTextArea2);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 420, 170));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
