package com.gui;

/**
 *
 * @author michael
 */
public class ReportesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportesJPanel
     */
    public ReportesJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        reportesjTable = new javax.swing.JTable();

        setForeground(new java.awt.Color(134, 61, 45));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reportesjTable.setForeground(new java.awt.Color(187, 78, 6));
        reportesjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(reportesjTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 790, 560));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable reportesjTable;
    // End of variables declaration//GEN-END:variables
}
