package com.gui;

import com.gui.menutienda.PokemonesJPanel;
import com.gui.menutienda.MedicinaJPanel;
import com.gui.menutienda.ComidaJPanel;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author michael
 */
public class VentanaPrincipalJFrame extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();
    /**
     * Creates new form Frame
     */
    public VentanaPrincipalJFrame() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/com/imagenes/fotos/LogoTitulo.png")).getImage());
        setSize(800, 570);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        contenedorJPanel = new FondoPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        botonPasear = new javax.swing.JMenu();
        botonMiPoke = new javax.swing.JMenu();
        botonTienda = new javax.swing.JMenu();
        botonTiendaComida = new javax.swing.JMenuItem();
        botonTiendaMedicamentos = new javax.swing.JMenuItem();
        botonTiendaPokemones = new javax.swing.JMenuItem();
        botonRevirir = new javax.swing.JMenuItem();
        botonReportes = new javax.swing.JMenu();
        botonAyuda = new javax.swing.JMenu();
        botonAyudaPasearjMenuItem = new javax.swing.JMenuItem();
        botonAyudaMiPokejMenuItem = new javax.swing.JMenuItem();
        ayudaTiendajMenuItem = new javax.swing.JMenuItem();
        ayudaReportesjMenuItem = new javax.swing.JMenuItem();
        botonAcercaDe = new javax.swing.JMenu();

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pokemon Memory");
        setBounds(new java.awt.Rectangle(800, 570, 570, 570));
        setIconImage(getIconImage());

        contenedorJPanel.setBackground(new java.awt.Color(153, 153, 153));
        contenedorJPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(contenedorJPanel, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setFont(new java.awt.Font("Meslo LG L DZ for Powerline", 0, 12)); // NOI18N

        botonPasear.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        botonPasear.setForeground(new java.awt.Color(0, 0, 0));
        botonPasear.setText("Pasear");
        botonPasear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonPasear.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        botonPasear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonPasearMousePressed(evt);
            }
        });
        jMenuBar1.add(botonPasear);

        botonMiPoke.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        botonMiPoke.setForeground(new java.awt.Color(0, 0, 0));
        botonMiPoke.setText("Mi Poke");
        botonMiPoke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonMiPokeMousePressed(evt);
            }
        });
        jMenuBar1.add(botonMiPoke);

        botonTienda.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        botonTienda.setForeground(new java.awt.Color(0, 0, 0));
        botonTienda.setText("Tienda");
        botonTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTiendaActionPerformed(evt);
            }
        });

        botonTiendaComida.setBackground(new java.awt.Color(0, 255, 153));
        botonTiendaComida.setForeground(new java.awt.Color(153, 102, 0));
        botonTiendaComida.setText("Comida");
        botonTiendaComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTiendaComidaActionPerformed(evt);
            }
        });
        botonTienda.add(botonTiendaComida);

        botonTiendaMedicamentos.setBackground(new java.awt.Color(51, 255, 153));
        botonTiendaMedicamentos.setForeground(new java.awt.Color(255, 0, 0));
        botonTiendaMedicamentos.setText("Medicina");
        botonTiendaMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTiendaMedicamentosActionPerformed(evt);
            }
        });
        botonTienda.add(botonTiendaMedicamentos);

        botonTiendaPokemones.setBackground(new java.awt.Color(102, 255, 153));
        botonTiendaPokemones.setForeground(new java.awt.Color(0, 153, 0));
        botonTiendaPokemones.setText("Pokemones");
        botonTiendaPokemones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTiendaPokemonesActionPerformed(evt);
            }
        });
        botonTienda.add(botonTiendaPokemones);

        botonRevirir.setBackground(new java.awt.Color(153, 255, 153));
        botonRevirir.setForeground(new java.awt.Color(255, 0, 0));
        botonRevirir.setText("Revivir Pokemon");
        botonRevirir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRevirirActionPerformed(evt);
            }
        });
        botonTienda.add(botonRevirir);

        jMenuBar1.add(botonTienda);

        botonReportes.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        botonReportes.setForeground(new java.awt.Color(0, 0, 0));
        botonReportes.setText("Reportes");
        botonReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonReportesMousePressed(evt);
            }
        });
        jMenuBar1.add(botonReportes);

        botonAyuda.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        botonAyuda.setForeground(new java.awt.Color(0, 0, 0));
        botonAyuda.setText("Ayuda");
        botonAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAyudaActionPerformed(evt);
            }
        });

        botonAyudaPasearjMenuItem.setText("Pasear");
        botonAyudaPasearjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAyudaPasearjMenuItemActionPerformed(evt);
            }
        });
        botonAyuda.add(botonAyudaPasearjMenuItem);

        botonAyudaMiPokejMenuItem.setText("Mis Pokemones");
        botonAyudaMiPokejMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAyudaMiPokejMenuItemActionPerformed(evt);
            }
        });
        botonAyuda.add(botonAyudaMiPokejMenuItem);

        ayudaTiendajMenuItem.setText("Tienda");
        ayudaTiendajMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaTiendajMenuItemActionPerformed(evt);
            }
        });
        botonAyuda.add(ayudaTiendajMenuItem);

        ayudaReportesjMenuItem.setText("Reportes");
        ayudaReportesjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaReportesjMenuItemActionPerformed(evt);
            }
        });
        botonAyuda.add(ayudaReportesjMenuItem);

        jMenuBar1.add(botonAyuda);

        botonAcercaDe.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        botonAcercaDe.setForeground(new java.awt.Color(0, 0, 0));
        botonAcercaDe.setText("Acerda de ...");
        botonAcercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAcercaDeMousePressed(evt);
            }
        });
        jMenuBar1.add(botonAcercaDe);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRevirirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRevirirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRevirirActionPerformed

    private void botonTiendaComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTiendaComidaActionPerformed
        // TODO add your handling code here:
        ComidaJPanel comida = new ComidaJPanel();
        this.cambiarPanel(comida);
    }//GEN-LAST:event_botonTiendaComidaActionPerformed

    private void botonTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTiendaActionPerformed

    }//GEN-LAST:event_botonTiendaActionPerformed

    private void botonTiendaMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTiendaMedicamentosActionPerformed
        // TODO add your handling code here:
        MedicinaJPanel medicina = new MedicinaJPanel();
        this.cambiarPanel(medicina);
    }//GEN-LAST:event_botonTiendaMedicamentosActionPerformed

    private void botonTiendaPokemonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTiendaPokemonesActionPerformed
        // TODO add your handling code here:
        PokemonesJPanel pokemones = new PokemonesJPanel();
        this.cambiarPanel(pokemones);
    }//GEN-LAST:event_botonTiendaPokemonesActionPerformed

    private void botonAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAyudaActionPerformed

    }//GEN-LAST:event_botonAyudaActionPerformed

    private void botonAyudaPasearjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAyudaPasearjMenuItemActionPerformed
        // TODO add your handling code here:
        String ayudaPasear = "	               -Pasear-\n"
                + "\n"
                + "· Al momento de sacar a pasear una mascota puede\n"
                + "  encontrarse con algún pokemon salvaje, comenzará una\n"
                + "  batalla donde es un juego de memorias, dependiendo\n"
                + "  del nivel de su pokemon será la cantidad de pares de\n"
                + "  cartas, gana el que tenga más parejas descubiertas.";

        JOptionPane.showMessageDialog(this, ayudaPasear);

    }//GEN-LAST:event_botonAyudaPasearjMenuItemActionPerformed

    private void botonAyudaMiPokejMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAyudaMiPokejMenuItemActionPerformed
        // TODO add your handling code here:
        String ayudaMiPoke = "	        -Mis Pokemones-\n"
                + "· Puede ver las mascotas que ha comprado y el\n"
                + "  estado en el que se encuentran, es decir, si\n"
                + "  tienen hambre, si necesitan limpieza, si han\n"
                + "  enfermado o si la mascota ha muerto.";

        JOptionPane.showMessageDialog(this, ayudaMiPoke);
    }//GEN-LAST:event_botonAyudaMiPokejMenuItemActionPerformed

    private void ayudaReportesjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaReportesjMenuItemActionPerformed
        // TODO add your handling code here:
        String ayudaReportes = "	            -Reportes-\n"
                + "\n"
                + "· Muesta una tabla donde se indica los movimientos\n"
                + "  hechos por cada mascota, como fecha de\n"
                + "  nacimiento, partidas ganadas, veces que ha\n"
                + "  enfermado, veces que ha comido, veces que ha\n"
                + "  enfermado y cuando ha muerto.";

        JOptionPane.showMessageDialog(this, ayudaReportes);
    }//GEN-LAST:event_ayudaReportesjMenuItemActionPerformed

    private void ayudaTiendajMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaTiendajMenuItemActionPerformed
        // TODO add your handling code here:
        String ayudaTienda = "   		  -Tienda-\n"
                + "\n"
                + "· En el menú de Tienda puede comprar diferentes\n"
                + "  articulos dependiendo de sus necesidades, al dar\n"
                + "  click en Tienda se le desplegará un listado\n"
                + "  donde puede comprar lo siguiente:\n"
                + "\n"
                + "· Comida: muestra un listado de diferentes alimentos\n"
                + "  que permite que la mascota sea menos propenso a\n"
                + "  enfermarse.\n"
                + "\n"
                + "· Medicamento: si en caso una de las mascota se enferma\n"
                + "  puede comprar algunos de los medicamentos disponibles\n"
                + "\n"
                + "  Pokemones: puede almacenar un máximo de 10 mascotas,\n"
                + "  si en caso aún tiene espacios disponibles puede comprar\n"
                + "  la mascota que desse.";
        JOptionPane.showMessageDialog(this, ayudaTienda);
    }//GEN-LAST:event_ayudaTiendajMenuItemActionPerformed

    private void botonAcercaDeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAcercaDeMousePressed
        // TODO add your handling code here:
        String acercaDe = "Version 1.0\nDesarrollado por estudiante de Introducción\n"
                + "a la programación y computación 1";
        JOptionPane.showMessageDialog(this, acercaDe);
    }//GEN-LAST:event_botonAcercaDeMousePressed

    private void botonPasearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPasearMousePressed
        // TODO add your handling code here:
        BatallaJPanel batalla = new BatallaJPanel();
        this.cambiarPanel(batalla);
    }//GEN-LAST:event_botonPasearMousePressed

    private void botonReportesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReportesMousePressed
        // TODO add your handling code here:
        ReportesJPanel reportes = new ReportesJPanel();
        this.cambiarPanel(reportes);
    }//GEN-LAST:event_botonReportesMousePressed

    private void botonMiPokeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMiPokeMousePressed
        // TODO add your handling code here:
        MiPokeJPanel miPoke = new MiPokeJPanel();
        this.cambiarPanel(miPoke);
    }//GEN-LAST:event_botonMiPokeMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ayudaReportesjMenuItem;
    private javax.swing.JMenuItem ayudaTiendajMenuItem;
    private javax.swing.JMenu botonAcercaDe;
    private javax.swing.JMenu botonAyuda;
    private javax.swing.JMenuItem botonAyudaMiPokejMenuItem;
    private javax.swing.JMenuItem botonAyudaPasearjMenuItem;
    private javax.swing.JMenu botonMiPoke;
    private javax.swing.JMenu botonPasear;
    private javax.swing.JMenu botonReportes;
    private javax.swing.JMenuItem botonRevirir;
    private javax.swing.JMenu botonTienda;
    private javax.swing.JMenuItem botonTiendaComida;
    private javax.swing.JMenuItem botonTiendaMedicamentos;
    private javax.swing.JMenuItem botonTiendaPokemones;
    private javax.swing.JPanel contenedorJPanel;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    public void cambiarPanel(JPanel panel) {
        contenedorJPanel.removeAll();
        contenedorJPanel.add(panel);
        contenedorJPanel.repaint();
        contenedorJPanel.revalidate();
    }

    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics foto) {
            imagen = new ImageIcon(getClass().getResource("/com/imagenes/fotos/FondoFrame.png")).getImage();

            foto.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);
            super.paint(foto);
        }
    }
}
